name: https://com39995.wordpress.com/
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ENLIGNEADS/https://com39995.wordpress.com/@v1.1.0
        with:
          directory: ./
